#!/usr/bin/php
<?
require_once('/standardebooks.org/web/lib/Core.php');

use function Safe\getopt;

function findObjectDifferences($fs, $db) {
	$diffs = [];
	$fsReflection = new ReflectionClass($fs);
	$dbReflection = new ReflectionClass($db);

	$fsProperties = $fsReflection->getProperties();
	$dbProperties = $dbReflection->getProperties();

	foreach ($fsProperties as $fsProperty) {
		$dbProperty = $dbReflection->getProperty($fsProperty->getName());

		// Make properties accessible for comparison
		$fsProperty->setAccessible(true);
		$dbProperty->setAccessible(true);

		print("\n" . $fsProperty->getName() . "\n");

		try{
			if($fsProperty->getName()[0] === '_') {
				// Property starts with underscore, remove it and call __get()
				$propertyNameWithoutUnderscore = substr($fsProperty->getName(), 1);
				//if($fsProperty->getType() === ReflectionProperty::TYPE_ARRAY){
				if(is_array($fsProperty->getValue($fs))){
					$arrayDiff = array_diff($fsProperty->getValue($fs), $dbProperty->getValue($db));
					if (!empty($arrayDiff)) {
						print('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' . "\n");
						print("Diff found in array property: " . $fsProperty->getName());
						print('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' . "\n");
						$diffs[$fsProperty->getName()] = ["fs" => $fsProperty->getValue($fs), "db" => $dbProperty->getValue($db)];
					}
					else{
						print('________________________________________________' . "\n");
						print_r('NO DIFF on array: ' . $fsProperty);
						print('________________________________________________' . "\n");
					}
				}
				else if ($fs->$propertyNameWithoutUnderscore !== $db->$propertyNameWithoutUnderscore) {
					print('++++++++++++++++++++++++++++++++++++++++++++++++' . "\n");
					print("Diff found on property: " . $fsProperty);
					print('++++++++++++++++++++++++++++++++++++++++++++++++' . "\n");
					$diffs[$fsProperty->getName()] = ["fs" => $fsProperty->getValue($fs), "db" => $dbProperty->getValue($db)];
				}
				else{
					print('________________________________________________' . "\n");
					print_r('NO DIFF on :' . $fsProperty);
					print('________________________________________________' . "\n");
				}
			}
			else if($fsProperty->getValue($fs) !== $dbProperty->getValue($db)) {
				print('================================================' . "\n");
				print_r('Diff on :' . $fsProperty);
				print('================================================' . "\n");
				$diffs[$fsProperty->getName()] = ["fs" => $fsProperty->getValue($fs), "db" => $dbProperty->getValue($db)];
			}
			else{
				print('________________________________________________' . "\n");
				print_r('NO DIFF on :' . $fsProperty);
				print('________________________________________________' . "\n");
			}
		}
		catch(Error $e){
			print('------------------------------------------------' . "\n");
			print_r('Missing property: ' . $fsProperty);
			print_r('Error: ' . $e);
			print('------------------------------------------------' . "\n");
		}
	}

	return $diffs;
}

$longopts = ['ebookWwwFilesystemPath:', 'verbose'];
$options = getopt('v', $longopts);

$ebookWwwFilesystemPath = $options['ebookWwwFilesystemPath'] ?? null;

$verbose = false;
if(isset($options['v']) || isset($options['verbose'])){
	$verbose = true;
}

if($ebookWwwFilesystemPath === null){
	print("Expected usage: update-ebook-database [-v,--verbose] --ebookWwwFilesystemPath <path>\n");
	exit(1);
}

if($verbose){
	print("ebookWwwFilesystemPath: $ebookWwwFilesystemPath\n");
}

$ebookFromFilesystem = Ebook::FromFilesystem($ebookWwwFilesystemPath);

if($verbose){
	print("Title: $ebookFromFilesystem->Title\n");
	print("Identifier: $ebookFromFilesystem->Identifier\n");
	print("TocEntries: " . print_r($ebookFromFilesystem->TocEntries, true));
	print("Collections: " . print_r($ebookFromFilesystem->Collections, true));
	print("Sources: " . print_r($ebookFromFilesystem->Sources, true));
}

$ebookFromFilesystem->CreateOrUpdate();

$ebookFromDatabase = Ebook::GetByIdentifier($ebookFromFilesystem->Identifier);

if($verbose){
	print("DB Title: $ebookFromDatabase->Title\n");
	print("DB Identifier: $ebookFromDatabase->Identifier\n");
	print("DB TocEntries: " . print_r($ebookFromDatabase->TocEntries, true));
	print("DB Collections: " . print_r($ebookFromDatabase->Collections, true));
	print("DB Sources: " . print_r($ebookFromDatabase->Sources, true));
}

print_r(findObjectDifferences($ebookFromFilesystem, $ebookFromDatabase));

// Check if array is empty. Print it and exit 1 if not.
// If verbose, print that the objects match
