#!/usr/bin/php
<?
require_once('/standardebooks.org/web/lib/Core.php');

$longopts = ['repoDir:', 'ebookWwwFilesystemPath:', 'verbose'];
$options = getopt('v', $longopts);

$repoDir = $options['repoDir'] ?? false;
$ebookWwwFilesystemPath = $options['ebookWwwFilesystemPath'] ?? false;

$verbose = false;
if(isset($options['v']) || isset($options['verbose'])){
	$verbose = true;
}

function NullIfEmpty($elements): ?string{
	if($elements === false){
		return false;
	}

	if(isset($elements[0])){
		$str = (string)$elements[0];
		if($str !== ''){
			return $str;
		}
	}

	return null;
}

if(!$repoDir || !$ebookWwwFilesystemPath){
	print("Expected usage: upsert-to-cover-art-database [-v] --repoDir <dir> --ebookWwwFilesystemPath <path>\n");
	exit(1);
}

if($verbose){
	print("repoDir: $repoDir\n");
	print("ebookWwwFilesystemPath: $ebookWwwFilesystemPath\n");
}

chdir($repoDir);
$contentOpf = shell_exec("git show HEAD:src/epub/content.opf");
$xml = new SimpleXMLElement(str_replace('xmlns=', 'ns=', $contentOpf));
$xml->registerXPathNamespace('dc', 'http://purl.org/dc/elements/1.1/');
$artistName = NullIfEmpty($xml->xpath('/package/metadata/dc:contributor[@id="artist"]'));

$rawColophon = file_get_contents($ebookWwwFilesystemPath . '/text/colophon.xhtml');
preg_match('|a painting completed \w+ (\d+)|ius', $rawColophon, $matches);
if(sizeof($matches) == 2){
	$year = (int)$matches[1];
}

$colophonXml = new SimpleXMLElement(str_replace('xmlns=', 'ns=', $rawColophon));
$title = NullIfEmpty($colophonXml->xpath('/html/body/main/section/p/i[@epub:type="se:name.visual-art.painting"]'));

if($verbose){
	print("artistName: $artistName\n");
	print("year: $year\n");
	print("title: $title\n");
}
